version: "3.8"

services:

  publishers-service:
    build: InterviewChallenge
    restart: always
    ports:
      - 8012:8012
    depends_on:
      - publishers-db
    stdin_open: true


  publishers-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'publishers'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - publishers-db:/var/lib/mysql

volumes:
  publishers-db:





